# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialize.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serialize.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fserialize.proto\"\xb7\x01\n\x0frequested_query\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x15\n\rbenchmarktype\x18\x02 \x01(\t\x12\x16\n\x0eworkloadmetric\x18\x03 \x01(\t\x12\x11\n\tbatchunit\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x14\n\x0c\x64\x61taset_type\x18\x07 \x01(\t\x12\x16\n\x0e\x64\x61ta_analytics\x18\x08 \x01(\t\"r\n\x0equery_response\x12\x0e\n\x06RFW_ID\x18\x01 \x01(\t\x12\x15\n\rlast_batch_ID\x18\x02 \x01(\x05\x12\x1d\n\x0bsample_data\x18\x03 \x03(\x0b\x32\x08.batches\x12\x1a\n\x12\x61nalytics_response\x18\x04 \x01(\x02\"$\n\x07\x62\x61tches\x12\x19\n\x11requested_samples\x18\x01 \x03(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTED_QUERY = _descriptor.Descriptor(
  name='requested_query',
  full_name='requested_query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFW_ID', full_name='requested_query.RFW_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='benchmarktype', full_name='requested_query.benchmarktype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workloadmetric', full_name='requested_query.workloadmetric', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batchunit', full_name='requested_query.batchunit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='requested_query.batch_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='requested_query.batch_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset_type', full_name='requested_query.dataset_type', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_analytics', full_name='requested_query.data_analytics', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=203,
)


_QUERY_RESPONSE = _descriptor.Descriptor(
  name='query_response',
  full_name='query_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RFW_ID', full_name='query_response.RFW_ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_batch_ID', full_name='query_response.last_batch_ID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_data', full_name='query_response.sample_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='analytics_response', full_name='query_response.analytics_response', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=319,
)


_BATCHES = _descriptor.Descriptor(
  name='batches',
  full_name='batches',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requested_samples', full_name='batches.requested_samples', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=357,
)

_QUERY_RESPONSE.fields_by_name['sample_data'].message_type = _BATCHES
DESCRIPTOR.message_types_by_name['requested_query'] = _REQUESTED_QUERY
DESCRIPTOR.message_types_by_name['query_response'] = _QUERY_RESPONSE
DESCRIPTOR.message_types_by_name['batches'] = _BATCHES

requested_query = _reflection.GeneratedProtocolMessageType('requested_query', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTED_QUERY,
  __module__ = 'serialize_pb2'
  # @@protoc_insertion_point(class_scope:requested_query)
  ))
_sym_db.RegisterMessage(requested_query)

query_response = _reflection.GeneratedProtocolMessageType('query_response', (_message.Message,), dict(
  DESCRIPTOR = _QUERY_RESPONSE,
  __module__ = 'serialize_pb2'
  # @@protoc_insertion_point(class_scope:query_response)
  ))
_sym_db.RegisterMessage(query_response)

batches = _reflection.GeneratedProtocolMessageType('batches', (_message.Message,), dict(
  DESCRIPTOR = _BATCHES,
  __module__ = 'serialize_pb2'
  # @@protoc_insertion_point(class_scope:batches)
  ))
_sym_db.RegisterMessage(batches)


# @@protoc_insertion_point(module_scope)
